### PR TITLE
add startup_checklist.html

### PR DESCRIPTION
**Pull request by dneise**
Also a startup_checklist was requested, it works like this.

Startup-person should check the webcams and start Main.js some time before startup, say 10 or 20 or 30 minutes .. whatever. If this is forgotten, shifthelper calls.

Things to be checked by the startup person include at the moment:

 * is the telescope still there (look at webcams)
 * is the schedule filled (otherwise main.js starts, but does nothing)
 * does the schedule need to be adjusted for common observation with swift.
 * -> start main.js and tick a box, saying that you really did it (maybe not needed, we have a check, which checks if main.js is actually running. we should simply let it start to check some time before the scheduled startup.)

### CODE REVIEW

**Comment by dneise** [comment]
can be looked at here, at the moment:

http://fact-project.org/sandbox/dneise/checklist_page/startup_checklist.html

**Comment by maxnoe** [comment]
I think the links should default to a new tab.

**Comment by dneise** [comment]
> I think the links should default to a new tab.
could you do that? I don't know how to do that

**Comment by dneise** [comment]
> I think the links should default to a new tab. 

done in 5f05a8c

**Pull request merged**
