### PR TITLE
Reactions & no email

### PR DESCRIPTION
**Pull request by dneise**
Add guides for shifters on what to do, in case something is wrong.
Remove (spam-)email

this repo is checked out in my sandbox and can be looked at here:
parking checklist: http://fact-project.org/sandbox/dneise/checklist_page/index.html
startup checklist: http://fact-project.org/sandbox/dneise/checklist_page/startup_checklist.html

### CODE REVIEW

**Comment by dneise** [comment]
Okay so I added the "try ONCE" and "call if still not good" columns as proposed by Adrian on the shutdown checklist. startup checklist not yet done.

**Comment by dadorner** [comment]
comments on start-up list
* "Camera Looks okay?" - what does 'okay' mean? not on fire? in park position? not open? 
could maybe a comparison picture be useful? 
* should we also add a check whether the mirror looks okay? if one is loose or fallen off that might be visible from the webcam and then it is probably better not to move the telescope
* also in case of ice the telescope should not be moved without inspection on site
* for the contact names you give - do you give the usernames of the logbook? then mine would be 'dorner' 
and does it maybe make sense to put a link to the ContactInfo page? 
* Ist the schedule -> Is the schedule

comments on shudown list: 
* for the drive issues - maybe also add a link to the corresponding trouble-shooting page
in some cases it might be easy to solve the problem, but maybe not with just trying to park again
* BiasVoltageOff - is it possible to implement that? at the point when the list is filled, bias can have only one state - either VoltageOff or Disconnected
* for the lid - it might be enough to send an email? (depends maybe a bit on the rest of the circumstances)
* I can't try now what happens if one submits with not having all boxes checked, but for preventing cases like it happened to Watz, to have an alert in case a box is not checked - something like 'are you sure the telescope is not parked? please call an expert immediately' (or more general 'you didn't check all boxes, please take the corresponding action'

**Comment by dneise** [comment]
> BiasVoltageOff - is it possible to implement that? at the point when the list is filled, bias can have only one state - either VoltageOff or Disconnected

This is the case at the moment yes. We'll have to discuss if and how to change this. But we do not want to check if the bias_ctrl_software is disconnected from the bias_crate_controller and thus unable to tell us anything about its state. But we want to make sure the Bias voltage is off. 

Only the second step is that we want to make sure that it cannot be switched on by somebody accidentally during daytime.

Possible ways to accomplish this task include:

 * parse the bais_ctrl logfile and print the last state before the current state
 * Invent a new "DisconnectedAfterBiasOff" state, that incorporates both information
 * do not allow to disconnect, when voltage is not off.
 * Do not even disconnect, but just "Lock". and do not allow to Lock from any other state then VoltageOff (similar to the Drive Lock after Park)

I guess there are more ways .. these just come to mind now.

**Comment by dneise** [comment]
> I can't try now what happens if one submits with not having all boxes checked, but for preventing cases like it happened to Watz, to have an alert in case a box is not checked - something like 'are you sure the telescope is not parked? please call an expert immediately' (or more general 'you didn't check all boxes, please take the corresponding action'

I'd say: Nothing happens. The check boxes are a mental help. One ticks them, when one check is done. It is like a checklist on a piece of paper, this list also does not remind you of a missing tick when you put it away thinking you've done everything. These paper lists are in use, and they do help. Why do we need more than that?

**Comment by dneise** [comment]
> "Camera Looks okay?" - what does 'okay' mean? 

I don't know. I think our starters can use common sense.

**Comment by dneise** [comment]
I still have to make it more beautiful...

**Comment by dadorner** [comment]
> >  I can't try now what happens if one submits with not having all boxes checked, but for preventing 
> > cases like it happened to Watz, to have an alert in case a box is not checked - something like 'are 
> > you sure the telescope is not parked? please call an expert immediately' (or more general 'you 
> > didn't check all boxes, please take the corresponding action'
> 
> I'd say: Nothing happens. The check boxes are a mental help. One ticks them, when one check is 
> done. It is like a checklist on a piece of paper, this list also does not remind you of a missing tick when 
> you put it away thinking you've done everything. These paper lists are in use, and they do help. Why 
> do we need more than that?

maybe because some points in the list are safety issues and shifters might be tired during shutdown
what does it harm to add an js-alert in case one of the checkboxes is not ticked? 
at least it might prevent cases like few days ago when the shifter just forgot to tick one checkbox
in addition, it might be useful to remind the shifter that in case he didn't tick one of the important checkboxes he/she has to do something ASAP

**Comment by dadorner** [comment]
> >  "Camera Looks okay?" - what does 'okay' mean?
> I don't know. I think our starters can use common sense.

among our shifters there are people who have never worked with such an instrument and/or who have never seen our telescope - of course most cases might be recognized by everybody and after some time the shifters get the experience how the camera and telescope are supposed to look like - but what if something strange happens on the first night of a new shifter?

**Comment by dneise** [comment]
> > >  "Camera Looks okay?" - what does 'okay' mean?
> > I don't know. I think our starters can use common sense.

> among our shifters there are people who have never worked with such an instrument and/or who have never seen our telescope - of course most cases might be recognized by everybody and after some time the shifters get the experience how the camera and telescope are supposed to look like - but what if something strange happens on the first night of a new shifter? 

Good question, how was this handled in the past? Did we not train new shifters?

**Comment by dneise** [comment]
> what does it harm to add an js-alert in case one of the checkboxes is not ticked? 

You are totally right. I doesn't harm at all.

**Comment by dneise** [comment]
Maybe I should point out the purpose of reviewing a PR, in my opinion.

The purpose is to find errors and mistakes, i.e. everything that invalidates the new version with respect to the existing version. So if the new version is made **worse** by a PR. This PR cannot be merged.

But if a PR can be made *even better* by adding more features, these features can still be added in a future PR. That is:

It is imho not an inherent problem of a PR if it does not include all possible features. 

---

Also, a feature branch opened by person A is not person A's private domain. Everybody is always welcome to improve. So if somebody wants to add some features to feature branch A, one can always branch off of A and create a new feature branch B and make a proposal to merge B into A **before** both get merged into the master.

However, often it is much easier to simply let A merge into the master and merge the new features in B into the master. 

Looking at the proposals above by @dadorner both the js-alert and the comparison image can be added anytime by anybody. A missing comparison image does imho not invalidate this PR, since it was missing before as well. A missing js-alert does not invalidate this PR, since it was missing before.

But I might be wrong with all this. It is after all my personal opinion.

**Pull request merged**
